server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    consul: #配置consul地址
      host: linshio.cn
      port: 8500
      discovery:
        # 发送心跳包的配置 坑
        heartbeat:
          enabled: true
        register: true
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service      # 匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
#            - After=2024-06-28T14:38:44.347408700+08:00[Asia/Shanghai] # 在该时间之后才能够达到触发的条件
#            - Before=2024-06-29T14:41:44.347408700+08:00[Asia/Shanghai] # 在该时间之前才能够达到触发的条件
#            - Between=2024-06-28T14:41:44.347408700+08:00[Asia/Shanghai],2024-06-28T14:42:44.347408700+08:00[Asia/Shanghai] # 在该时间之间才能够达到触发的条件
#            - Cookie=username,linshio # 需要携带该cookie才能达到触发的条件
#            - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Host=**.linshio.cn # 请求头要有Host属性并且值为linshio.cn
#            - Query=username, \d+  # 要有参数名username并且值还要是整数才能路由
#            - RemoteAddr=192.168.1.1/24 # 外部访问我的IP限制，最大跨度不超过32，目前是1~24它们是 CIDR 表示法。
#            - Method=GET #表示只能够使用该请求方式
        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由