server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.182.1:8848         #Nacos服务注册中心地址
  # ==========applicationName + druid-mysql8 driver===================
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://60.204.128.243:3307/seata_order?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: LingXi666
# ========================mybatis===================
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.linshio.cloud.entities
  configuration:
    map-underscore-to-camel-case: true

# ========================seata===================
seata:
  registry: # seata注册配置
    type: nacos # seata注册类型
    nacos:
      application: seata-server #seata应用名称
      server-addr: 60.204.128.243:8848
      namespace: ""
      group: SEATA_GROUP
      cluster: default
  config:             # seata配置抓取
    nacos:
      server-addr: 60.204.128.243:8848
      namespace: ""
      group: SEATA_GROUP
      username: nacos
      password: nacos
  tx-service-group: default_tx_group # 事务组，由它获得TC服务的集群名称
  service:
    vgroup-mapping:
      default_tx_group: default # 事务群组的映射配置关系
  data-source-proxy-mode: AT
  application-id: seata-server

logging:
  level:
    io:
      seata: info